spring.application.name=facerecognition

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.datasource.url=jdbc:postgresql://localhost:5434/reg
spring.datasource.username=postgres
spring.datasource.password=456123456



spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JSP View Resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

app.jwt.secret=vfyugvfsrgkhknkgyur6456rvi87te434sfvkh9i6fgvjtd5e45wess3srexhgyut7b7ggt67thliu9y7ghbjk99y78gceseg
app.jwt.expiration-ms=86400000
